"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

*Note! When this finishes, you must then manually add two things to the app (show package contents/Contents. Those things are Tcl and Tk, found at /anaconda/lib/[tcl8.5 tk8.5])
"""

from setuptools import setup
import os

os.system('export TCL_LIBRARY=/anaconda/lib/tcl8.5')
os.system('export TK_LIBRARY=/anaconda/lib/tk8.5')

APP = ['mouse_tracker.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True, 'packages':[]}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
